# Generated by Django 2.2.5 on 2019-09-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', 'changed_imageF_in_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
