# Generated by Django 2.2.5 on 2019-09-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='screenshot_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Доп. скриншот 1'),
        ),
        migrations.AddField(
            model_name='game',
            name='screenshot_2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Доп. скриншот 2'),
        ),
        migrations.AddField(
            model_name='game',
            name='screenshot_3',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Доп. скриншот 3'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото обложки'),
        ),
    ]
