# Generated by Django 2.2.5 on 2019-09-09 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_auto_20190909_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
    ]
