# Generated by Django 2.2.5 on 2019-09-17 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_game_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
