# Generated by Django 2.2.5 on 2019-09-17 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_game_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Shooters', 'Shooters'), ('Racing', 'Racing')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
