# Generated by Django 2.2.5 on 2019-09-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_auto_20190917_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.CharField(choices=[('&#9734; &#9734; &#9734; &#9734; &#9734;', '1'), ('&#9733; &#9734; &#9734; &#9734; &#9734;', '2'), ('&#9733; &#9733; &#9734; &#9734; &#9734;', '3'), ('&#9733; &#9733; &#9733; &#9733; &#9734;', '4'), ('&#9733; &#9733; &#9733; &#9733; &#9733;', '5')], max_length=255),
        ),
    ]
