# Generated by Django 2.2.5 on 2019-09-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', 'created_game_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание игры'),
        ),
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(default='', upload_to='Shop/photos', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название игры'),
        ),
    ]
